### PR TITLE
Fix: Path to exceptions now relative to scripts

### PR DESCRIPTION
**Pull request by simson-sillage**
So that the repository can be placed elsewhere than at ~

### CODE REVIEW

**Comment by bmwiedemann** [comment]
There are more exception files used in `rebuild` script... and maybe we could make it a directory, so that we use `$somepath/exceptions/neardate` to make the whole checkout less messy

**Comment by simson-suse** [comment]
I added a `exceptions/` subdirectory and also adjusted the paths in `rebuild`. Do you like it?

**Comment by bmwiedemann** [comment]
looks nice. There is one edge case when calling via bash and $PATH
```
> bash -x rbk
+++ pwd
++ basename /home/bernhard/code/osc/t/openSUSE:Factory/python-sure
+ pkg=python-sure
+ years=15
++ dirname rbk
+ grep -q '^python-sure$' ./exceptions/neardate
grep: ./exceptions/neardate: No such file or directory
```

`$BASH_SOURCE` instead of `$0` seems to work, but maybe there is another way.
Or we just ignore it and merge as is.

**Comment by jdsn** [comment]
@bmwiedemann 
Please elaborate on the issue. This is not an issue for us an our shells :)

**Comment by simson-suse** [comment]
@bmwiedemann Nevermind I got it reproduced. But BASH_SOURCE is not unix shell compatible, so it wont work on your debian system with `#!/bin/sh` shebang.

**Pull request merged**
